name: test

on:
  push:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm turbo info
      - run: ./test.sh
